export default (sequelize, DataTypes) => {
    const PropertySummery = sequelize.define('PropertySummery', {
        propertyId: { type: DataTypes.INTEGER },
        propertyName: { type: DataTypes.STRING },
        propertyCode: { type: DataTypes.STRING },
        ownerEmail: { type: DataTypes.STRING },
        ownerFirstName: { type: DataTypes.STRING },
        ownerLastName: { type: DataTypes.STRING },
        ownerMobile: { type: DataTypes.STRING },
        propertyEmailId: { type: DataTypes.STRING },
        propertyMobileNumber: { type: DataTypes.STRING },
        createdAt: { type: DataTypes.DATE },
        noOfRooms: { type: DataTypes.INTEGER },
        approved: { type: DataTypes.INTEGER },
        status: { type: DataTypes.INTEGER },
        locality: { type: DataTypes.STRING },
        cityName: { type: DataTypes.STRING },
        stateName: { type: DataTypes.STRING },
        hubName: { type: DataTypes.STRING },
        zone: { type: DataTypes.STRING },
        onboardedRooms: { type: DataTypes.INTEGER },
        roomsCommission: { type: DataTypes.INTEGER },
        approvedBy: { type: DataTypes.STRING },
        approvedByName: { type: DataTypes.STRING },
        createdByName: { type: DataTypes.STRING },
        createdBy: { type: DataTypes.STRING },
        reSubmitted: { type: DataTypes.BOOLEAN },
        onboarded_date: { type: DataTypes.DATE },
        remarks: { type: DataTypes.TEXT },
        agreement: { type: DataTypes.INTEGER },
        SRC: { type: DataTypes.INTEGER },
        propertyStatus: { type: DataTypes.STRING },
        PendingRooms: { type: DataTypes.INTEGER },
        LiveRooms: { type: DataTypes.INTEGER },
        SoldOutRooms: { type: DataTypes.INTEGER },
        BlockedRooms: { type: DataTypes.INTEGER },
    }, {
        tableName: 'propertySummery',
        timestamps: true,
    });
    return PropertySummery;
};